### ISSUE TITLE
@Inject JobContext fails: a JobExecution is required

### ISSUE THREAD

**Issue by wrungel** [codecentric/spring-boot-starter-batch-web#59]
Execution of following Batchlet fails:

```java
import javax.batch.api.AbstractBatchlet;
import javax.batch.runtime.context.JobContext;
import javax.inject.Inject;

public class BatchletWithJobContextInjection extends AbstractBatchlet {
    @Inject
    private JobContext jobContext;

    @Override
    public String process() {
        return "OK";
    }
}
```

Stacktrace:
```
javax.batch.operations.JobStartException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchletWithJobContextInjection': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.batch.runtime.context.JobContext de.codecentric.batch.simplejsr.item.BatchletWithJobContextInjection.jobContext; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'jsr_jobContext': org.springframework.beans.factory.FactoryBeanNotInitializedException: A JobExecution is required

	at org.springframework.batch.core.jsr.launch.JsrJobOperator.start(JsrJobOperator.java:635)
	at org.springframework.batch.test.JsrTestUtils.runJob(JsrTestUtils.java:58)
	at de.codecentric.batch.simplejsr.BatchletWithJobContextInjectionJsr352Test.testTraditionalJsr352(BatchletWithJobContextInjectionJsr352Test.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'batchletWithJobContextInjection': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.batch.runtime.context.JobContext de.codecentric.batch.simplejsr.item.BatchletWithJobContextInjection.jobContext; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'jsr_jobContext': org.springframework.beans.factory.FactoryBeanNotInitializedException: A JobExecution is required
	at org.springframework.batch.core.jsr.configuration.support.SpringAutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(SpringAutowiredAnnotationBeanPostProcessor.java:272)
	at org.springframework.batch.core.jsr.configuration.support.JsrAutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(JsrAutowiredAnnotationBeanPostProcessor.java:30)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:572)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.batch.core.jsr.launch.JsrJobOperator.start(JsrJobOperator.java:633)
	... 24 more
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private javax.batch.runtime.context.JobContext de.codecentric.batch.simplejsr.item.BatchletWithJobContextInjection.jobContext; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'jsr_jobContext': org.springframework.beans.factory.FactoryBeanNotInitializedException: A JobExecution is required
	at org.springframework.batch.core.jsr.configuration.support.SpringAutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(SpringAutowiredAnnotationBeanPostProcessor.java:501)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91)
	at org.springframework.batch.core.jsr.configuration.support.SpringAutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(SpringAutowiredAnnotationBeanPostProcessor.java:269)
	... 36 more
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'jsr_jobContext': org.springframework.beans.factory.FactoryBeanNotInitializedException: A JobExecution is required
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:135)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1645)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1175)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:327)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1135)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062)
	at org.springframework.batch.core.jsr.configuration.support.SpringAutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(SpringAutowiredAnnotationBeanPostProcessor.java:473)
	... 38 more
```
See error in action: [BatchletWithJobContextInjectionJsr352Test.java](https://github.com/wrungel/spring-boot-starter-batch-web/blob/injectJobContext/batch-web-spring-boot-samples/batch-boot-simple-jsr352/src/test/java/de/codecentric/batch/simplejsr/BatchletWithJobContextInjectionJsr352Test.java)

The following combinations fail with the same error:
* `@Inject org.springframework.batch.core.scope.context.JobContext`
* `@Autowired org.springframework.batch.core.scope.context.JobContext`
* `@Inject javax.batch.runtime.context.JobContext`
* `@Autowired javax.batch.runtime.context.JobContext`

Also injection into `javax.batch.api.partition.PartitionMapper` fails with the same error.

**Comment by wrungel** [comment]
Surprisingly 
`@Inject javax.batch.runtime.context.JobContext` 

### works only in:
`javax.batch.api.partition.PartitionMapper`.

### doesn't work in:
* `javax.batch.api.chunk.ItemReader` 
* `javax.batch.api.chunk.ItemWriter` 
* `javax.batch.api.chunk.ItemProcessor`
* `javax.batch.api.partition.PartitionMapper`

**Comment by wrungel** [comment]
In order `@Inject JobContext` works, the scope of the injection target Spring Bean must be "_step_" or "_job_":
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
                              http://www.springframework.org/schema/beans/spring-beans.xsd">
    <bean id="myBatchlet" class="com.example.MyBatchlet" scope="step"/>
</beans>
```

See [Reference Doc](https://docs.spring.io/spring-batch/trunk/reference/html/configureStep.html#step-scope).
